### ISSUE TITLE
Multiple definitions exist for class 'Builder'

### ISSUE THREAD

**Issue by kyoya0819** [mpyw/eloquent-has-by-non-dependent-subquery#7]
Thank you for providing great package.

This repository's Laravel IDE Helper cause Class Duplicate Error.
I think `_laravel_ide_helper.php` don't need.

![image](https://user-images.githubusercontent.com/45027336/106381680-d1a41800-63fd-11eb-8b9b-d5eefc294ed4.png)

つたない英語ですがすみません。。

**Comment by mpyw** [comment]
@kyoya0819 

I'm sorry, but this is the **intended design**. It is impossible to achieve completion for Laravel in IDEs without preparing duplicate dummy classes due to magic methods, delegation, macros and so on. [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) which is frequently used for developing Laravel applications behaves in the same way.

You have two choices:

- Disable the same type of notifications in the IDE settings
- Remove `_laravel_ide_helper.php` after running `composer install`

**Comment by kyoya0819** [comment]
正確な文意を伝えたいので日本語で失礼します。（通知に気づかず返信遅くなり申し訳ございません）
IDEの補完機能が使えないとのことですが、必要ならば各ModelでPhpDocumentのmethodを定義すれば良いのではないでしょうか？もしくは、Commandを定義し、必要ならば当該ファイルを生成すれば良いのではないでしょうか？

どちらにせよ、IDEの補完機能が使えずにエラーが出るのを回避するために、重複のエラーがでているのは本末転倒だと考えます。

**Comment by mpyw** [comment]
> IDEの補完機能が使えずにエラーが出るのを回避するために、重複のエラーがでているのは本末転倒だと考えます。

自分が必ずしもそうではないと考える理由がこうです。

- クラス重複もメソッド存在不明も，どちらもデフォルトでは Error ではなく Warning レベル以下で，深刻度はむしろクラス重複のほうが低く設定されている（灰色の下線が出るだけで黄色くハイライトすらされない）
- 実装が全く不明な状態で完全なダックタイピングを行うよりは，実装の可能性が2通りに絞れている方が型安全の観点からは優れていて，コードを書く上で Typo を防ぐなどの実利をもたらしている
- laravel-ide-helper が Laravel 開発において広く受け入れられていると自分は認識していて，使用者の立場からすればクラス重複定義に関しては無視する運用が定着していると思われる

> Commandを定義し、必要ならば当該ファイルを生成すれば良いのではないでしょうか？

1つ問題があるとすれば，「IDE を使っているが laravel-ide-helper を使っていない」という人を考慮できていないということですが… 多くの人は「IDE を使っていない」か「IDE と laravel-ide-helper を両方使っている」のいずれかに該当するはずで，意図的に laravel-ide-helper を入れていない人は他に比べて少ない気がしております。また仮にそういった人たちは重複の指摘が気になるのであれば，自分でインストール後にファイル削除するコマンドを整備する，などはできると思うんですよね。

それゆえ，デフォルトで補完用のファイルが存在しているほうが望ましいと，今のところは考えています。このファイルを添付することによるメリット・デメリットはどちらも把握した上で，メリットのほうが大きいと判断し，意図的にそうしていることになります。

> 各ModelでPhpDocumentのmethodを定義すれば良いのではないでしょうか？

ちなみに `Model` の `@method` 定義では， `$this` のチェーンが `static` `self` `Builder` になった瞬間に `Model` 側に書いた補完が一切でなくなるので，全然使い物にならないです…

-------

IDE で発生する指摘に関しては問題無いと考える一方， PHPStan や Psalm などでのエラーが回避できないとしたら実害があるので，後ほど対応をするかもしれません。
