### ISSUE TITLE
Make it compatible with multiple database connections in different servers?

### ISSUE THREAD

**Issue by rust17** [mpyw/eloquent-has-by-non-dependent-subquery#8]
Hi, It's not a bug but a feature want to be added;
Is it possible to make it available for crossing multiple database connection?
For example
```
// App\Models\Company
class Company extends Model
{
    .
    .
    .
    public function supplier()
    {
        return $this->hasOne(Supplier::class);
    }
    .
    .
    .
}

// App\Models\Supplier
class Supplier extends Model
{
    .
    .
    .
    public function __construct($attributes = [])
    {
        parent::__construct($attributes);

        $connection = config('database.supply');

        $table = $this->getTable();

        $this->setConnection($connection);

         $this->setTable(config('database.connections.'.$connection.'.database').'.'.$table);
    }
    .
    .
    .
}
```

When I need to get the Company models that contains supplier, using laravel wherehas
```
Company::whereHas('supplier')->get();
```
It's not support. For detail, see [#33402](https://github.com/laravel/framework/issues/33402). The main reason is that laravel merge two tables into one sql. Like: 
```
select count(*) as aggregate from `companies` where exists (select * from `supply`.`suppliers` where `companies`.`id` = `supply`.`suppliers`.`company_id`))
```
 It will ignore database1 connection.

By using hasByNonDependentSubquery:
```
Company::hasByNonDependentSubquery('supplier')->get();
```
Sql : 
``` 
select count(*) as aggregate from `companies` where `companies`.`id` in (select `supply`.`suppliers`.`company_id` from `supply`.`suppliers`))
```
Also just one sql. It's it possible to make it split to two sql? Thanks a lot.

**Comment by mpyw** [comment]
@rust17 I've checked the following package.

- [hoyvoy/laravel-cross-database-subqueries: Eloquent cross database compatibility in subqueries](https://github.com/hoyvoy/laravel-cross-database-subqueries)

While it looks useful, the implementation of the library is quite complex. I'm worrying about we get into spaghetti codes. Since the macros provided by my library **focuses only on the generation of the query** and **leave its execution to the user**, it's so hard to separate it into two queries.

Personally, I think it would be better to explicitly separate queries when crossing databases. If you are not willing to write such statements in controllers or models, try the *CleanArchitecture-like* pattern that introduces **UseCase** classes.

- [5年間 Laravel を使って辿り着いた，全然頑張らない「なんちゃってクリーンアーキテクチャ」という落としどころ](https://zenn.dev/mpyw/articles/ce7d09eb6d8117) (in Japanese)

**Comment by rust17** [comment]
This [package](https://github.com/hoyvoy/laravel-cross-database-subqueries) I have already tried. It add the `database` and `table` prefix in the sql but still one sql. When cross different server database, as I mentioned one sql don't work . 

> It will ignore database1 connection

I think may be fork it to make a new package. Thanks for reply. By the way, your article is great. I may try to use the `use case` in my project.
